config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :ignore_reminders

  root 'welcome#index'
  
  resources :subscriptions

  resources :reminders, only: :index

  resources :channels do
    resources :reminders
  end

  devise_for :users

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  belongs_to :user
  has_many :subscription, :dependent => :destroy
  has_many :reminders, :dependent => :destroy
  validates_presence_of :name, :user_id

  def self.search(search, user)
    if search
      where("user_id != ? AND is_public = true AND name LIKE ?", user.id, "%#{search}%")
    else
      where("user_id != ? AND is_public = true", user.id)
    end
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_channel, only: [:show, :edit, :update, :destroy]
  before_filter :validate_owner, only: [:edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = current_user.channels
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = current_user.channels.create(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:user_id, :name, :description, :password, :is_public)
    end

    def validate_owner
      if (@channel.user != current_user)
        redirect_to @channel
      end
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_for(@channel, html: {autocomplete: 'off', class: 'col l12'}) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <input type="password" style="display:none">
  <div class="row">
    <div class="input-field col l6">
      <%= f.text_field :name, autocomplete: 'off', class: 'validate' %>
      <%= f.label :name %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col l6">
      <%= f.text_field :description, autocomplete: 'off', class: 'validate' %>
      <%= f.label :description %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col l6">
      <%= f.password_field :password, autocomplete: 'off', class: 'validate' %>
      <%= f.label :password %>
    </div>
  </div>

  <div class="row">
    <div class="col l6">
      <%= f.check_box :is_public %>
      <label for="channel_is_public">This is a public channel</label>
    </div>
  </div>
  
  <div class="row">
    <div class="col l6">
      <%= f.button class: "btn waves-effect" %>
      <%= link_to 'Cancel', channels_path, class: 'waves-effect btn-flat' %>
    </div>
  </div>
<% end %>

app/views/channels/edit.html.erb
<div class="row">
  <div class="col s12 m12 l12">
    <div class="section">
      <h2 class="header">Editing: <%= @channel.name %></h2>
      <div class="row">  
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/channels/index.html.erb
<div class="row">
  <div class="col s12 m12 l12">
    <div class="section">
      <h2 class="header">My channels</h2>
      <div class="row">  
        <div class="col l12">
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Public</th>
                <th></th>
              </tr>
            </thead>
          
            <tbody>
              <% @channels.each do |channel| %>
                <tr>
                  <td><%= channel.name %></td>
                  <td><%= channel.description %></td>
                  <td><%= channel.is_public ? "Public" : "Private" %></td>
                  <td class="fit">
                    <%= link_to 'Show', channel, class: 'btn waves-effect' %>
                    <%#= link_to 'Edit', edit_channel_path(channel), class: 'btn waves-effect' %>
                    <%= link_to 'New reminder', new_channel_reminder_path(channel), class: 'btn waves-effect' %>
                    <%#= link_to 'Delete', channel, method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect btn-flat' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      
      <div class="row">  
        <div class="col l12">
          <%= link_to 'New Channel', new_channel_path, class: 'waves-effect btn-large' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/channels/new.html.erb
<div class="row">
  <div class="col s12 m12 l12">
    <div class="section">
      <h2 class="header">New channel</h2>
      <div class="row">  
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/channels/show.html.erb
<div class="row">
  <div class="col s12 m12 l12">
    <div class="section">
      <h2 class="header"><%= @channel.name %></h2>
      <div class="row">  
        <div class="col l12">
          <p>
            <%= @channel.description %>
          </p>
          <table class="table">
            <thead>
              <tr>
                <th>Title</th>
                <th>Note</th>
                <th>Start</th>
                <th>End</th>
                <th>Is public</th>
                <th>Repeated</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @channel.reminders.each do |reminder| %>
                <% if reminder.is_public || reminder.user == current_user %>
                  <tr>
                    <td><%= reminder.title %></td>
                    <td><%= reminder.note %></td>
                    <td><%= local_time(reminder.start) %></td>
                    <td><%= local_time(reminder.end) %></td>
                    <td><%= reminder.is_public ? "Public" : "Private" %></td>
                    <td><%= reminder.repeated ? "Repeats" : "Once" %></td>
                    <td class="fit">
                      <%= link_to 'Show', channel_reminder_path(reminder.channel, reminder), class: 'waves-effect btn' %>
                      <%# if reminder.user == current_user || @channel.user == current_user %>
                        <%#= link_to 'Edit', edit_channel_reminder_path(reminder.channel, reminder), class: 'waves-effect btn' %>
                        <%#= link_to 'Delete', channel_reminder_path(reminder.channel, reminder), method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect btn-flat' %>
                      <%# end %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      
      <div class="row">  
        <div class="col l12">
          <%= link_to 'New reminder', new_channel_reminder_path(@channel), class: 'waves-effect btn-large' %>
          
          <% if @channel.user == current_user %>
            <%= link_to 'Edit channel', edit_channel_path(@channel), class: 'waves-effect btn' %>
            <%= link_to 'Delete', channel_path(@channel), method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect btn-flat red-text' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>