config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :ignore_reminders

  root 'welcome#index'
  
  resources :subscriptions

  resources :reminders, only: :index

  resources :channels do
    resources :reminders
  end

  devise_for :users

end

app/views/partials/_navbar.html.erb
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">one</a></li>
  <li><a href="#!">two</a></li>
  <li class="divider"></li>
    <li>
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
      <% else %>
        <%= link_to('Login', new_user_session_path)  %>  
      <% end %>
    </li>
</ul>
<nav>
  <div class="container">
    <div class="nav-wrapper">
    <%= link_to "RemindUs", root_path, class: 'brand-logo' %>
      <ul class="right hide-on-med-and-down">
        <li class="<% if controller.controller_name == "subscriptions"%>active<%end%>"><%= link_to 'Subscriptions', subscriptions_path, class: 'waves-effect' %></li>
        <li class="<% if controller.controller_name == "channels"%>active<%end%>"><%= link_to 'My channels', channels_path, class: 'waves-effect' %></li>
        <li class="<% if controller.controller_name == "reminders"%>active<%end%>"><%= link_to 'Reminders', reminders_path, class: 'waves-effect' %></li>
        <!-- Dropdown Trigger -->
        <li><a class="dropdown-button waves-effect" href="#!" data-beloworigin="true" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
    </div>
  </div>
</nav>