config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :ignore_reminders

  root 'welcome#index'
  
  resources :subscriptions

  resources :reminders, only: :index

  resources :channels do
    resources :reminders
  end

  devise_for :users

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :channel
  has_many :reminders, through: :channel
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/new
  def new
    @channels = Channel.search(params[:search], current_user)
    @subscription = current_user.subscriptions.new
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = current_user.subscriptions.create(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription.channel, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription = Subscription.find(params[:id])
    if @subscription.user != current_user
      redirect_to subscriptions
    end
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:channel_id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/index.html.erb
<div class="bs-docs-section">
  <div class="page-header">
      <div class="row">
      <div class="col-lg-12">
        <h1>Subscribed channels</h1>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <table class="table">
        <thead>
          <tr>
            <th>Channel</th>
            <th>Description</th>
            <th>User</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @subscriptions.each do |subscription| %>
            <tr>
              <td><%= link_to subscription.channel.name, channel_path(subscription.channel) %></td>
              <td><%= subscription.channel.description %></td>
              <td><%= subscription.user.email %></td>
              <td class="fit"><%= link_to 'Unsubscribe', subscription_path(subscription), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-flat waves-effect' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'Search', new_subscription_path, class: 'btn-large waves-effect' %>
    </div>
  </div>
</div>

app/views/subscriptions/new.html.erb
<div class="row">
  <div class="col s12 m12 l12">
    <div class="section">
      <h2 class="header">Search channels</h2>
      <div class="row">  
        <form action="?" class="col l12">
          <div class="row">
            <div class="input-field col l12">
              <input type="text" name="search" class="validate">
              <label for="search">Search</label>
            </div>
          </div>
        </form>
      </div>
      <div class="row">
        <div class="col l12">
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th></th>
              </tr>
            </thead>
          
            <tbody>
              <% @channels.each do |channel| %>
                <tr>
                  <td><%= link_to channel.name, channel %></td>
                  <td><%= channel.description %></td>
                  <td class="fit">
                    <%= form_for @subscription do |f| %>
                      <%= f.text_field :channel_id, value: channel.id, hidden: true %>
                      <%= f.button 'Subscribe', class: 'btn waves-effect' %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>