config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :ignore_reminders

  root 'welcome#index'
  
  resources :subscriptions

  resources :reminders, only: :index

  resources :channels do
    resources :reminders
  end

  devise_for :users

end

app/models/ignore_reminder.rb
class IgnoreReminder < ActiveRecord::Base
  belongs_to :user
  belongs_to :reminder
end

app/controllers/ignore_reminders_controller.rb
class IgnoreRemindersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ignore_reminder, only: [:show, :edit, :update, :destroy]

  # GET /ignore_reminders
  # GET /ignore_reminders.json
  def index
    @ignore_reminders = IgnoreReminder.all
  end

  # GET /ignore_reminders/1
  # GET /ignore_reminders/1.json
  def show
  end

  # GET /ignore_reminders/new
  def new
    @ignore_reminder = IgnoreReminder.new
  end

  # GET /ignore_reminders/1/edit
  def edit
  end

  # POST /ignore_reminders
  # POST /ignore_reminders.json
  def create
    @ignore_reminder = IgnoreReminder.new(ignore_reminder_params)

    respond_to do |format|
      if @ignore_reminder.save
        format.html { redirect_to @ignore_reminder, notice: 'Ignore reminder was successfully created.' }
        format.json { render :show, status: :created, location: @ignore_reminder }
      else
        format.html { render :new }
        format.json { render json: @ignore_reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ignore_reminders/1
  # PATCH/PUT /ignore_reminders/1.json
  def update
    respond_to do |format|
      if @ignore_reminder.update(ignore_reminder_params)
        format.html { redirect_to @ignore_reminder, notice: 'Ignore reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @ignore_reminder }
      else
        format.html { render :edit }
        format.json { render json: @ignore_reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ignore_reminders/1
  # DELETE /ignore_reminders/1.json
  def destroy
    @ignore_reminder.destroy
    respond_to do |format|
      format.html { redirect_to ignore_reminders_url, notice: 'Ignore reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ignore_reminder
      @ignore_reminder = IgnoreReminder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ignore_reminder_params
      params.require(:ignore_reminder).permit(:user_id, :reminder_id)
    end
end

app/helpers/ignore_reminders_helper.rb
module IgnoreRemindersHelper
end

app/views/ignore_reminders/_form.html.erb
<%= form_for(@ignore_reminder) do |f| %>
  <% if @ignore_reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ignore_reminder.errors.count, "error") %> prohibited this ignore_reminder from being saved:</h2>

      <ul>
      <% @ignore_reminder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :reminder_id %><br>
    <%= f.text_field :reminder_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ignore_reminders/edit.html.erb
<h1>Editing ignore_reminder</h1>

<%= render 'form' %>

<%= link_to 'Show', @ignore_reminder %> |
<%= link_to 'Back', ignore_reminders_path %>

app/views/ignore_reminders/index.html.erb
<h1>Listing ignore_reminders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Reminder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ignore_reminders.each do |ignore_reminder| %>
      <tr>
        <td><%= ignore_reminder.user %></td>
        <td><%= ignore_reminder.reminder %></td>
        <td><%= link_to 'Show', ignore_reminder %></td>
        <td><%= link_to 'Edit', edit_ignore_reminder_path(ignore_reminder) %></td>
        <td><%= link_to 'Destroy', ignore_reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ignore reminder', new_ignore_reminder_path %>

app/views/ignore_reminders/new.html.erb
<h1>New ignore_reminder</h1>

<%= render 'form' %>

<%= link_to 'Back', ignore_reminders_path %>

app/views/ignore_reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @ignore_reminder.user %>
</p>

<p>
  <strong>Reminder:</strong>
  <%= @ignore_reminder.reminder %>
</p>

<%= link_to 'Edit', edit_ignore_reminder_path(@ignore_reminder) %> |
<%= link_to 'Back', ignore_reminders_path %>